### ISSUE TITLE
getting an error on the example run

### ISSUE THREAD

**Issue by andrewcz** [Bo-Ning/Bayesian-multivariate-time-series-causal-inference#1]
MultivariateCausalInferenceRes <- 
+   two.stage.estimation(test.data, cntl.index, cntl.data, 
+                        graph = graph, graph.structure = graph.structure, 
+                        circle = nseasons, causal.period = causal.period, 
+                        s = 0.1,
+                        emvs.iteration = 50, 
+                        v0.value = seq(1e-6, 0.02, length.out = 5),
+                        mcmc.iterloop = iterloop, burnin = burnin, 
+                        stationary = TRUE, 
+                        misspecification = FALSE,
+                        num.sim.data = 30, num.cores = 1,
+                        seed = 1, probs = 0.95,
+                        plot.EMVS.figure = FALSE,
+                        plot.title = "EMVS plot")
Starting Bayesian EM variable selection... 
  |                                                                                                             |   0%
 Show Traceback
 
 Rerun with Debug
 Error in rgwish(adj.g = graph.structure, b = n + 1, D = k1^2 * n * diag(n))[,  : 
  incorrect number of dimensions > 
> # collect results

**Comment by andrewcz** [comment]
![screenshot_2018-10-03_15-25-37](https://user-images.githubusercontent.com/2296335/46391473-7758f680-c720-11e8-8a76-eedcc5572378.png)

**Comment by yc-ning** [comment]
I guess you are using windows to run this R code. The ``rgwish'' package is slightly different from MacBook to windows.

**Comment by andrewcz** [comment]
I am using Linux to run the code.
Will update that package though.
Best,
Andrew
